apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: gdi-mini-node-configmap
    files:
      - config/app.yaml
      - config/beacon-aggregated.yaml
      - config/beacon-sensitive.yaml
      - config/beacon-common.yaml
      - config/fdp.yaml

generatorOptions:
  disableNameSuffixHash: true
