apiVersion: v1
kind: Service
metadata:
  name: gdi-mini-node-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gdi-mini-node
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: http
